name: RLC Scraper - Test Co Minutę

on:
  schedule:
    - cron: "0 11/4 * * *"  # CRON dla zimy
  # cron dla lata
#      schedule:
  #  - cron: "0 4,8,12,16,20 * * *"

  workflow_dispatch:      # dodatkowo możliwość ręcznego odpalenia

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Pobierz repozytorium
        uses: actions/checkout@v4

      - name: Instalacja zależności
        run: pip install requests gspread google-auth python-dotenv

      - name: Uruchom scraper
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: python rlc-stats.py